services:
  - type: web
    name: backend-cybercmq
    runtime: node
    buildCommand: npm install && npx prisma generate
    startCommand: npx tsx src/index.ts
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cybercmq
          property: connectionString
      - key: JWT_SECRET
        value: secret
